version: "3.9"

services:
  web:
    build:
      context: ./src/manga-reader-webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
