version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "manga-reader"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '5171:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: root
  redis:
    image: redis:6.0.9
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  api_v1:
    build:
      context: ./services/api/v1
      dockerfile: Dockerfile
    container_name: api_v1
    restart: always
    ports:
      - "5172:5172"
    depends_on:
      - mysql
      - redis
    environment:
      - MANGADEX_API_BASE_URL=https://api.mangadex.org
      - REDIS_ADDR=http://redis:6379
      - PORT=5172
  app:
   build:
      context: ./services/app
      dockerfile: Dockerfile
   container_name: app
   restart: always
   ports:
      - "5173:5173"
   environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=manga-reader
   
volumes:
  db-data:
