version: "3.9"

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
      - '6603:3306'
      environment:
         MYSQL_ROOT_PASSWORD: helloworld

   phpmyadmin:
      depends_on:
      - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
      - '8080:80'
      environment:
         PMA_HOST: db
   web:
      build:
         context: ./src/manga-reader-webapp
         dockerfile: Dockerfile
      ports:
         - "3000:3000"
      depends_on:
         - redis
         - db
   redis:
      image: "redis:alpine"
